version: '3.3'
services:

  backend:
    network_mode: host
    restart: always
    build: .
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    command: >
      gunicorn accompanist.main:app
      --workers ${NUM_WORKERS}
      --worker-class uvicorn.workers.UvicornWorker
      --bind=127.0.0.1:${FASTAPI_PORT}
    volumes:
    - ./storage-volume:/storage
    environment:
    - STORAGE_PATH=/storage

  celery-worker:
    network_mode: host
    restart: always
    build: .
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    command:
      celery -A accompanist.celery.main.app worker --loglevel info -E --concurrency ${CELERY_CONCURRENCY}
    volumes:
      - ./storage-volume:/storage
    environment:
      - STORAGE_PATH=/storage
    deploy: # GPU is used only by celery worker
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]


  frontend:
    restart: always
    ports:
      - ${DEPLOYMENT_HOST}:${DOCKER_FRONTEND_PORT}:80
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NGINX_PORT: ${NGINX_PORT}
        DEPLOYMENT_HOST: ${DEPLOYMENT_HOST}

  nginx: # for serving lots of static files & redirecting to FastAPI
    image: nginx:latest
    restart: always
    network_mode: host
    env_file: .env
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ${STORAGE_PATH}:/usr/share/nginx/html/static
    
  db:
    image: postgres:16
    restart: always
    ports:
    - ${DB_PORT}:5432
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
        - postgres-volume:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_PORT}:5672

volumes:
  postgres-volume:
  # ./storage-volume is used as a bind mount
